src/Entity/Session.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\SessionRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $sessionName = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $startDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $endDate = null;

    #[ORM\Column]
    private ?int $numberPlace = null;

    /**
     * @var Collection<int, Trainee>
     */
    #[ORM\ManyToMany(targetEntity: Trainee::class, inversedBy: 'sessions')]
    private Collection $trainees;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Training $training = null;

    /**
     * @var Collection<int, Program>
     */
    #[ORM\OneToMany(targetEntity: Program::class, mappedBy: 'session')]
    private Collection $programs;

    public function __construct()
    {
        $this->trainees = new ArrayCollection();
        $this->programs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSessionName(): ?string
    {
        return $this->sessionName;
    }

    public function setSessionName(string $sessionName): static
    {
        $this->sessionName = $sessionName;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): static
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): static
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getNumberPlace(): ?int
    {
        return $this->numberPlace;
    }

    public function setNumberPlace(int $numberPlace): static
    {
        $this->numberPlace = $numberPlace;

        return $this;
    }

    /**
     * @return Collection<int, Trainee>
     */
    public function getTrainees(): Collection
    {
        return $this->trainees;
    }

    public function addTrainee(Trainee $trainee): static
    {
        if (!$this->trainees->contains($trainee)) {
            $this->trainees->add($trainee);
            $trainee->addSession($this);
        }

        return $this;
    }

    public function removeTrainee(Trainee $trainee): static
    {
        $this->trainees->removeElement($trainee);

        return $this;
    }

    public function getTraining(): ?Training
    {
        return $this->training;
    }

    public function setTraining(?Training $training): static
    {
        $this->training = $training;

        return $this;
    }

    /**
     * @return Collection<int, Program>
     */
    public function getPrograms(): Collection
    {
        return $this->programs;
    }

    public function addProgram(Program $program): static
    {
        if (!$this->programs->contains($program)) {
            $this->programs->add($program);
            $program->setSession($this);
        }

        return $this;
    }

    public function removeProgram(Program $program): static
    {
        if ($this->programs->removeElement($program)) {
            // set the owning side to null (unless already changed)
            if ($program->getSession() === $this) {
                $program->setSession(null);
            }
        }

        return $this;
    }

    public function getBeginningDate(): ?string {
        return $this->startDate->format('d.m.Y');
    }

    public function getEndingDate(): ?string {
        return $this->endDate->format('d.m.Y');
    }

    public function getStatut(): ?string {
        $now = new \DateTime();
        if($this->startDate > $now) {
            return "upcoming";
        } else if ($this->startDate <= $now && $this->endDate >= $now) {
            return "currently";
        } else {
        return "finished";
        }
    }

    public function countTrainees(): int
    {
        return count($this->trainees);
    }

    public function getRemainingPlaces(int $numberPlace): int
    {
        return $numberPlace - $this->countTrainees();
    }
  


    public function __toString()
    {
        return $this->sessionName;
    }
}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\Session;
use App\Entity\Trainee;
use App\Entity\Training;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;


class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        //On précise le type de chaque entrée pour pouvoir filtrer les champs
            ->add('sessionName', TextType::class )
            ->add('startDate', DateType::class, [
                'widget' => 'single_text',
            ])
            ->add('endDate', DateType::class, [
                'widget' => 'single_text',
            ])
            ->add('numberPlace', IntegerType::class )
            
            ->add('training', EntityType::class, [
                'class' => Training::class,
                'choice_label' => 'trainingName',
            ])
            ->add('Valider', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use App\Entity\Program;
use App\Entity\Session;
use App\Form\ProgramType;
use App\Form\SessionType;
use Doctrine\ORM\EntityManager;
use App\Repository\ProgramRepository;
use App\Repository\SessionRepository;
use App\Repository\TraineeRepository;
use Symfony\Component\Form\FormError;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class SessionController extends AbstractController
{
    #[Route('/session', name: 'app_session')]
    public function index(SessionRepository $sessionRepository, EntityManagerInterface $entityManager): Response
    {
        $sessions = $sessionRepository->findBy([], ["startDate" => "ASC"]);

        $statutsSession = [
            'upcoming' => [],
            'currently' => [],
            'finished' => []
        ];

        foreach ($sessions as $session) {
            $statut = $session->getStatut();
            $statutsSession[$statut][] = $session;
        }
        return $this->render('session/index.html.twig', [
            'sessions' => $sessions,
            'statutsSession' => $statutsSession,
        
        ]);
    }

    #[Route('/session/new', name: 'new_session')]
    public function new(Request $request , EntityManagerInterface $entityManager): Response
    {
        $session = new Session();

        $form = $this->createForm(SessionType::class, $session);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $startDate = $session->getStartDate();
            $endDate = $session->getEndDate();
                    if($startDate > $endDate) {
                        $form->addError(new FormError('The ending date is earlier than the beginning date '));
                    } else {
                    $session = $form->getData();
                    $entityManager->persist($session);
                    $entityManager->flush();

                    return $this->redirectToRoute('app_session');
                    }
                }

        return $this->render('session/new.html.twig', [
            'formAddSession' => $form,
        ]);

        
    }


    #[Route('/session/{id}/removeTrainee/{traineeId}', name: 'removeTrainee_session')]
    public function removeTraineeSession($id, $traineeId, EntityManagerInterface $entityManager, SessionRepository $sessionRepository, TraineeRepository $traineeRepository): Response
    {
        $session = $sessionRepository->find($id);
        $trainee = $traineeRepository->find($traineeId);

        $session->removeTrainee($trainee);
        $entityManager->persist($session);
        $entityManager->flush();

        return $this->redirectToRoute('show_session',['id' => $id] );
     
        
    }

    #[Route('/session/{id}/addTrainee/{traineeId}', name: 'addTrainee_session')]
    public function addTraineeSession($id, $traineeId, EntityManagerInterface $entityManager, SessionRepository $sessionRepository, TraineeRepository $traineeRepository): Response
    {
        $session = $sessionRepository->find($id);
        $trainee = $traineeRepository->find($traineeId);

        $session->addTrainee($trainee);
        $entityManager->persist($session);
        $entityManager->flush();

        return $this->redirectToRoute('show_session',[
            'id' => $id,
            'session' => $session,
            'trainee' => $trainee
        ] );
    }

    #[Route('/session/{id}/removeProgram/{programId}', name: 'removeProgram_session')]
    public function removeProgramSession($id, $programId, EntityManagerInterface $entityManager, SessionRepository $sessionRepository, ProgramRepository $programRepository): Response
    {
        $session = $sessionRepository->find($id);
        $program = $programRepository->find($programId);

        $session->removeProgram($program);
        $entityManager->persist($session);
        $entityManager->flush();

        return $this->redirectToRoute('show_session',['id' => $id] );
     
        
    }

    #[Route('/session/{id}/addProgram/{programId}', name: 'addProgram_session')]
    public function addProgramSession($id, $programId, EntityManagerInterface $entityManager, SessionRepository $sessionRepository, ProgramRepository $programRepository): Response
    {
        $session = $sessionRepository->find($id);
        $program = $programRepository->find($programId);

        $session->addProgram($program);
        $entityManager->persist($session);
        $entityManager->flush();

        return $this->redirectToRoute('show_session',['id' => $id] );
    }


    #[Route('/session/{id}', name: 'show_session')]
    public function show(Session $session = null, SessionRepository $sr, Request $request , EntityManagerInterface $entityManager): Response 
    {
        $notRegistered = $sr->findNotRegistered($session->getId());
        $notProgrammed = $sr->findNotProgrammed($session->getId());

        //on crée un nouvel objet program
        $program = new Program();
        
        //on crée le formulaire
        $formAddProgram = $this->createForm(ProgramType::class, $program);
        $formAddProgram->handleRequest($request);
        if ($formAddProgram->isSubmitted() && $formAddProgram->isValid()) {

                    $program = $formAddProgram->getData();
                    $entityManager->persist($program);
                    $entityManager->flush();
        
                    return $this->redirectToRoute('show_session', ['id' => $session->getId()]);
        
    }

    $totalPlaces = $session->getNumberPlace();
    $takenPlaces = $session->countTrainees();
    $remainingPlaces = $session->getRemainingPlaces($totalPlaces);

        return $this->render('session/show.html.twig', [
            'notRegistered'=> $notRegistered,
            'notProgrammed'=> $notProgrammed,
            'session' => $session,
            'formAddProgram' => $formAddProgram->createView(),
            'takenPlaces' => $takenPlaces,
            'remainingPlaces' => $remainingPlaces,
        ]);
    }


}

templates/session/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}List of sessions{% endblock %}

{% block body %}
    <div class="wrapper-list-session">

    <h1> List of sessions</h1>

        <h2>Upcoming Sessions :</h2>
            {% for session in statutsSession['upcoming'] %}
            <li> <a href="{{ path('show_session', {'id' : session.id} )}}"> {{ session }} </a> ({{ session.beginningDate }} - {{ session.endingDate }})  <br> </li>
            {% endfor %}
        <h2>Current Sessions :</h2>
            {% for session in statutsSession['currently'] %}
            <li> <a href="{{ path('show_session', {'id' : session.id} )}}"> {{ session }} </a> ({{ session.beginningDate }} - {{ session.endingDate }}) <br>  </li>
            {% endfor %}

        <h2>Finished Sessions :</h2>
            {% for session in statutsSession['finished'] %}
            <li> <a href="{{ path('show_session', {'id' : session.id} )}}"> {{ session }} </a> ({{ session.beginningDate }} - {{ session.endingDate }}) <br> </li>
            {% endfor %}

       {# {% for session in sessions %}
        <a href="{{ path('show_session', {'id' : session.id} )}}"> {{ session }}</a> ({{ session.beginningDate}} - {{ session.endingDate}})<br>
        {% endfor %} #}
    </div>
{% endblock %}

templates/session/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add a session{% endblock %}

{% block body %}
<div class="form-session">
    <h1>Add a session</h1>
        {{ form_start(formAddSession) }}
            {{ form_row(formAddSession.sessionName) }}
            {{ form_row(formAddSession.startDate) }}
            {{ form_row(formAddSession.endDate) }}
            {{ form_row(formAddSession.numberPlace) }}
            {{ form_row(formAddSession.training) }}
            <div class="submit">
                {{ form_row(formAddSession.Valider) }}
            </div>
        </div>
        {{ form_end(formAddSession) }}
</div>
   

{% endblock %}

templates/session/removeTrainee.html.twig
{% extends 'base.html.twig' %}

{% block title %}Title{% endblock %}

{% block body %}
{% endblock }

templates/session/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Details of the session{% endblock %}

{% block body %}
<div class="detail-session">
    <h1> Details of the session {{ session }}</h1>
        <h2>Program: </h2> <br>
            <div class="info-session">
               <li> <span>Beginning date : </span> {{ session.beginningDate}} </li> <br>
               <li> <span>Ending date : </span> {{ session.endingDate}} </li> <br>
               <li> <span>Number of places : </span> {{ session.numberPlace}} </li><br>
                <li> <span>Token places : </span>{{takenPlaces}} </li> <br>
                <li> <span>Remaining places : </span> {{ remainingPlaces }} </li> <br>
            </div>
    <div class="modules-session">
        <h3>Modules:</h3> 
            {% for program in session.programs %}
                {% if is_granted('ROLE_ADMIN') %}
                <div class="module-session">
                    <a href="{{ path('removeProgram_session', {'id': session.id, 'programId': program.id} )}}"> <i class="fa-solid fa-trash"></i> </a>
                    {% endif %}
                    <a href={{ path('show_module', {'id':program.module.id} )}}> {{ program.module }} </a> <a href={{ path('show_category', {'id':program.module.category.id} )}}> - {{ program.module.Category }} </a><span> -  {{ program.nbDays }} days </span><br>
            </div>
        {% endfor %}
    </div>
        <h2>Trainees registered in this session :</h2> <br>
            {% for trainee in session.trainees %} 
                <li>
                    <a href="{{ path('show_trainee', {'id':trainee.id} )}}">{{ trainee }}</a>
                    {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{ path('removeTrainee_session', {'id': session.id, 'traineeId': trainee.id} )}}"> <i class="fa-solid fa-trash"></i> </a>
                    {% endif %}
                </li>  <br> 
            {% endfor %}

        <h2>Trainees not registered in this session :</h2>
            {% for trainee in notRegistered %}
                <li>
                    <a href="{{ path('show_trainee', {'id':trainee.id} )}}">{{ trainee }}</a>
                    {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{ path('addTrainee_session', {'id': session.id, 'traineeId': trainee.id} )}}"> <i class="fa-solid fa-plus"></i> </a>
                    {% endif %}
                    
                </li>
                {% endfor %}
                
                <h2> Modules not programmed in this session : </h2> <br>
                {% for module in notProgrammed %}
            
                <li>
                    <a href="{{ path('show_module', {'id':module.id} )}}">{{ module }}</a>
                </li>
                
            {% endfor %}
                {% if is_granted('ROLE_ADMIN') %}
                <div class="form-program">
                    <h1>Add a program</h1>
                        {{ form_start(formAddProgram) }}
                            {{ form_row(formAddProgram.nbDays) }}
                            {{ form_row(formAddProgram.session) }}
                            {{ form_row(formAddProgram.module) }}
                            <div class="submit">
                                {{ form_row(formAddProgram.Valider) }}
                            </div>
                        
                        {{ form_end(formAddProgram) }}
                    </div>
                </div>
        
        {% endif %}
    </div>
{% endblock %}