src/Entity/Trainee.php
<?php

namespace App\Entity;

use App\Repository\TraineeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TraineeRepository::class)]
class Trainee
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $surname = null;

    #[ORM\Column(length: 50)]
    private ?string $firstname = null;

    #[ORM\Column(length: 50)]
    private ?string $gender = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $birthDate = null;

    #[ORM\Column(length: 50)]
    private ?string $city = null;

    #[ORM\Column(length: 50)]
    private ?string $emailTrainee = null;

    #[ORM\Column(length: 50)]
    private ?string $phone = null;

    #[ORM\Column(length: 50)]
    private ?string $adress = null;

    #[ORM\Column(length: 50)]
    private ?string $zipCode = null;

    /**
     * @var Collection<int, Session>
     */
    #[ORM\ManyToMany(targetEntity: Session::class, mappedBy: 'trainees')]
    private Collection $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): static
    {
        $this->surname = $surname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): static
    {
        $this->gender = $gender;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTimeInterface $birthDate): static
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getEmailTrainee(): ?string
    {
        return $this->emailTrainee;
    }

    public function setEmailTrainee(string $emailTrainee): static
    {
        $this->emailTrainee = $emailTrainee;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    public function setZipCode(string $zipCode): static
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): static
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
            $session->addTrainee($this);
        }

        return $this;
    }

    public function removeSession(Session $session): static
    {
        if ($this->sessions->removeElement($session)) {
            $session->removeTrainee($this);
        }

        return $this;
    }

    public function getAge(): ?string 
    {
        $now = new \DateTime();
        $interval = $this->birthDate->diff($now);
        return $interval->format("%Y");
    }

    public function getFullAdress()
    {
        return $this->adress." ".$this->city." ".$this->zipCode;
    }

    public function getBirthday(): ?string {
        return $this->birthDate->format('d.m.Y');
    }
    
    public function __toString()
    {
        return $this->surname." ".$this->firstname;
    }
}

src/Form/TraineeType.php
<?php

namespace App\Form;

use App\Entity\Session;
use App\Entity\Trainee;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class TraineeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('surname', TextType::class)
            ->add('firstname', TextType::class)
            ->add('gender', TextType::class)
            ->add('birthDate', DateType::class, [
                'widget' => 'single_text',
            ])
            ->add('city', TextType::class)
            ->add('emailTrainee', TextType::class)
            ->add('phone', TextType::class)
            ->add('adress', TextType::class)
            ->add('zipCode', TextType::class)
            ->add('Valider', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Trainee::class,
        ]);
    }
}

src/Controller/TraineeController.php
<?php

namespace App\Controller;

use App\Entity\Trainee;
use App\Form\TraineeType;
use Doctrine\ORM\EntityManager;
use App\Repository\TraineeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TraineeController extends AbstractController
{
    #[Route('/trainee', name: 'app_trainee')]
    public function index(TraineeRepository $traineeRepository): Response
    {
        $trainees = $traineeRepository->findBy([], ["firstname" => "ASC"]);
        return $this->render('trainee/index.html.twig', [
            'trainees' => $trainees
        
        ]);
    }

    #[Route('/trainee/new', name: 'new_trainee')]
    public function new(Request $request , EntityManagerInterface $entityManager): Response
    {
        $trainee = new Trainee();

        $form = $this->createForm(TraineeType::class, $trainee);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $trainee = $form->getData();
            $entityManager->persist($trainee);
            $entityManager->flush();

            return $this->redirectToRoute('app_trainee');
        }

        return $this->render('trainee/new.html.twig', [
            'formAddTrainee' => $form,
        ]);

    }

    #[Route('/trainee/{id}', name: 'show_trainee')]
    public function show(Trainee $trainee): Response 
    {
        return $this->render('trainee/show.html.twig', [
            'trainee' => $trainee
        ]);
    }


}

templates/trainee/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}List of trainees{% endblock %}

{% block body %}
<div class="wrapper-list-trainee">
    <h1> List of trainees</h1>

        {% for trainee in trainees %}
        
        <li> <a href="{{ path('show_trainee', {'id':trainee.id} )}}">{{ trainee }} </a> ( {{ trainee.phone}} ) </li><br> 
       
        {% endfor %}
    </div>
{% endblock %}

templates/trainee/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add a trainee{% endblock %}

{% block body %}
<div class="form-trainee">
    <h1>Add a trainee</h1>
        {{ form_start(formAddTrainee) }}
            {{ form_row(formAddTrainee.surname) }}
            {{ form_row(formAddTrainee.firstname) }}
            {{ form_row(formAddTrainee.gender) }}
            {{ form_row(formAddTrainee.birthDate) }}
            {{ form_row(formAddTrainee.city) }}
            {{ form_row(formAddTrainee.emailTrainee) }}
            {{ form_row(formAddTrainee.phone) }}
            {{ form_row(formAddTrainee.adress) }}
            {{ form_row(formAddTrainee.zipCode) }}
            <div class="submit">
                {{ form_row(formAddTrainee.Valider) }}
            </div>
        </div>
        {{ form_end(formAddTrainee) }}
</div>  
{% endblock %}

templates/trainee/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Details of trainees{% endblock %}

{% block body %}
    <div class="detail-trainee">
        <h1> Details of trainees</h1>
        <div class="info-trainee">
            <h2> {{ trainee }}</h2>
               <li> <span>Name :</span> {{ trainee }} </li><br>
               <li> <span>Gender :</span> {{ trainee.gender }}</li> <br>
               <li> <span>Born on </span>:{{ trainee.birthday }}</li> <br>
               <li> <span>Age:</span> {{ trainee.age }} years old </li><br>
               <li> <span>Adress : </span>{{ trainee.fullAdress }} </li><br>
               <li> <span>Email :</span>{{ trainee.emailTrainee }} </li><br>
               <li> <span>Phone number :</span>{{ trainee.phone }}</li> <br>
        </div>
        <div class="session-trainee">
        <h2>List of registered sessions</h2>

            {% for session in trainee.sessions %}
            <a href="{{ path('show_session', {'id' : session.id} )}}"> {{ session }}</a> <br>
            
            {% endfor %}
        </div>
    </div>

    
{% endblock %}